---
when:
  branch: main
  event: [ push, pull_request]

steps:
  fmt:
    image: nixos/nix:2.25.2
    commands:
      - echo 'experimental-features = flakes nix-command' >> /etc/nix/nix.conf
      - nix develop -c nixpkgs-fmt --check .
