---
when:
  - branch: main
    event: [ push, pull_request]

steps:
  - name: fmt
    image: nixos/nix:2.32.1
    commands:
      - echo 'experimental-features = flakes nix-command' >> /etc/nix/nix.conf
      - nix develop -c nixpkgs-fmt --check .
